### ISSUE TITLE
log4net.config file 

### ISSUE THREAD

**Issue by abrasat** [serilog-contrib/serilog-formatting-log4net#50]
Is there any Serilog.Formatting.Log4Net setting available, which tells log4net to read the configuration from a log4net.config file ?

**Comment by 0xced** [comment]
It looks like you misunderstood the purpose of this package. `Serilog.Formatting.Log4Net` does not depend on log4net, it produces logs which are _XML format compatible_ with logs produced by log4net and log4j.

As such, it would not make any sense for the formatter provided in this package to read a log4net configuration file.

**Comment by abrasat** [comment]
@0xced  Ok, thanks for the clarification. Is it possible to set a rolling interval (for instance daily) for the xml log files, and write max.30 log files (the oldest should be deleted)?

**Comment by 0xced** [comment]
Yes it's possible but again, this is not this project responsibility. Serilog is a very modular project and you want to use the [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) package to write log events to a file.
